
name: meu_app_flutter
description: App de espiritualidade (Flutter + dat)
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.4.12
  pay: ^3.2.1
  flutter_stripe: ^12.0.2
  http: ^1.2.2
  flutter_local_notifications: ^19.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gpay.json
    - assets/applepay.json
    - assets/cartas_do_dia/
    - assets/cartas_do_dia_org/
