
name: meu_app_flutter
description: App de espiritualidade (Flutter + dat)
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.4.12
  pay: ^3.2.1
  flutter_stripe: ^12.0.2
  http: ^1.2.2
  flutter_local_notifications: ^19.4.1
  url_launcher: ^6.3.0
  video_player: ^2.8.7
  mask_text_input_formatter: ^2.9.0
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.7.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/gpay.json
    - assets/applepay.json
    - assets/cartas_do_dia/
    - assets/cartas_do_dia_org/
    - assets/parceiros/
    - assets/conteudo/
    - assets/audios_cartas_dia/
    - assets/audios_cartas_org/
